name: .NET
on:
  push:
    branches: [ main ]
    paths: 
    - 'apis/poi/**.csproj'
    - 'apis/poi/**.cs'
    - 'apis/poi/**.sln'
    paths-ignore:
    - 'apis/poi/README.md'
  pull_request:
    branches: [ main ]
    paths: 
    - 'apis/poi/**.csproj'
    - 'apis/poi/**.cs'
    - 'apis/poi/**.sln'
    paths-ignore:
    - 'apis/poi/README.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
