name: .NET
on:
  push:
    branches: [ main , dotnet-pipeline ]
    paths: 
    - 'apis/poi/**.csproj'
    - 'apis/poi/**.cs'
    - 'apis/poi/**.sln'
    - '.github/workflows/dotnet.yml'
  pull_request:
    branches: [ main ]
    paths: 
    - 'apis/poi/**.csproj'
    - 'apis/poi/**.cs'
    - 'apis/poi/**.sln'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
       working-directory: 'apis/poi'
     
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - uses: nashmaniac/create-issue-action@v1.1
      name: Create Issue Action
      if: ${{ failure() }}
      with: 
        title: Build Failed
        token: ${{secrets.GITHUB_TOKEN}}
        assignees: ${{github.actor}}
        labels: worflow-failed
        body: Workflow failed for commit ${{github.sha}}
