name: Go

on:
  push:
    branches: [ main, go-pipeline ]
    paths: 
    - 'apis/trips/go.mod'
    - 'apis/trips/main.go'
    - 'apis/trips/trips'
    - '.github/workflows/go.yml'
  pull_request:
    branches: [ main ]
    paths: 
    - 'apis/trips/go.mod'
    - 'apis/trips/main.go'
    - 'apis/trips/trips'

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
       working-directory: 'apis/trips'
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v

    - name: Test
      run: go test /tripgo -run Unit
    - uses: nashmaniac/create-issue-action@v1.1
      name: Create Issue Action
      if: ${{ failure() }}
      with: 
        title: Build Failed
        token: ${{secrets.GITHUB_TOKEN}}
        assignees: ${{github.actor}}
        labels: worflow-failed
        body: Workflow failed for commit ${{github.sha}}
