# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ main , java-pipeline ]
    paths: 
    - 'apis/user-java/'
    - '.github/workflows/maven-publish.yml'
  pull_request:
    branches: [ main ]
    paths: 
    - 'apis/user-java/'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
       working-directory: 'apis/user-java/'

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
       # server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
       # settings-path: 'apis/user-java/pom.xml' # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests with Maven
      run: mvn -B test --file pom.xml
