name: User Profile Build
on:
  push:
    branches: [ main , user-profile-pipeline ]
    paths: 
    - 'apis/userprofile/'
    - '.github/workflows/node.yml'

  pull_request:
    branches: [ main ]
    paths: 
    - 'apis/userprofile/'
    - '.github/workflows/node.yml'

env:
  NODE_VERSION: '10.x'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
       working-directory: 'apis/userprofile'
     
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install
      run: |
        npm install

    - name: npm build
      run: |
        npm run build --if-present

    - name: npm test
      run: 
        npm run test --if-present

    - uses: nashmaniac/create-issue-action@v1.1
      name: Create Issue Action
      if: ${{ failure() }}
      with: 
        title: Build Failed
        token: ${{secrets.GITHUB_TOKEN}}
        assignees: ${{github.actor}}
        labels: worflow-failed
        body: Workflow failed for commit ${{github.sha}}
