name: Build POI Container

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Create and Deploy POI to Azure'

  push:
    branches: '*'
    paths: 
    - 'apis/poi/**.csproj'
    - 'apis/poi/**.cs'
    - 'apis/poi/**.sln'
    - '.github/workflows/dotnet.yml'
    - '.github/workflows/poi-dotnet-docker-build.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
       working-directory: 'apis/poi/web'
       
    steps:

    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURECREDENTIALS }}
        
    - name: Build and push
      run: |
        az acr login -n openhackh9786t04acr
        docker build . -t openhackh9786t04acr.azurecr.io/devopsoh/api-poi:${{ github.sha }}
        docker push openhackh9786t04acr.azurecr.io/devopsoh/api-poi:${{ github.sha }} 

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhackh9786t04poi'
        images: 'openhackh9786t04acr.azurecr.i/devopsoh/api-poi:${{ github.sha }}'
