name: Build POI Container

on:
  push:
    branches: '*'
    paths: 
    - 'apis/poi/**.csproj'
    - 'apis/poi/**.cs'
    - 'apis/poi/**.sln'
    - '.github/workflows/dotnet.yml'
    - '.github/workflows/poi-dotnet-docker-build.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
       
       
    steps:

    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURECREDENTIALS }}
        
    - name: Build and push
      working-directory: 'apis/poi/web'
      run: |
        az acr login -n openhackh9786t04acr
        docker build . -t openhackh9786t04acr.azurecr.io/devopsoh/api-poi:${{ github.run_number }}
        docker push openhackh9786t04acr.azurecr.io/devopsoh/api-poi:${{ github.run_number }} 
    
    # Always deploy to staging
    
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhackh9786t04poi'
        images: 'openhackh9786t04acr.azurecr.io/devopsoh/api-poi:${{ github.run_number }}'
        slot-name: 'staging'
        
    # Test staging to see if it works
    - name: Test Staging
      run: |
        bash ./polling.sh https://openhackh9786t04poi-staging.azurewebsites.net/api/healthcheck/poi
        
    # needs: build-and-deploy
    # Swap
    
    # Test prod to make sure it works
    
    # Optional: rollback if prod has issues
