on: 
    push:
    branches: [ main ]
    paths: 
    - 'apis/poi/**.csproj'
    - 'apis/poi/**.cs'
    - 'apis/poi/**.sln'	
name: Linux_Container_POI_Workflow
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURECREDENTIALS }}

       
    - run: |
	az acr login -n openhackh9786t04acr
        docker build . -t openhackh9786t04acr.azurecr.io/devopsoh/api-poi:${{ github.sha }}
        docker push openhackh9786t04acr.azurecr.io/devopsoh/api-poi:${{ github.sha }} 

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhackh9786t04poi'
        images: 'openhackh9786t04acr.azurecr.i/devopsoh/api-poi:${{ github.sha }}'
