name: Test Staging

on:
  push:
    branches: '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
       
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
      
    - name: Test Staging
      run: |
        echo "current directory"
        pwd
        echo "show directory"
        ls
        bash ~/$GITHUB_REPOSITORY/polling.sh https://openhackh9786t04poi-staging.azurewebsites.net/api/healthcheck/poi
